### ISSUE TITLE
Compilation Warning 

### ISSUE THREAD

**Issue by nightfall708** [yazid/iOS-TOTP#1]
Hi,
There's a warning here:

`return [NSString stringWithFormat:@"%0*lu", digits_, pinValue];`

which says:

`/Users/.../OTPGenerator.m:145:42: Field width should have type 'int', but argument has type 'NSUInteger' (aka 'unsigned long')`

**Comment by yazid** [comment]
Hmm.. What's your current environment? I ran it through both Xcode 5.1.1 and 6.0 beta, I don't seem to be getting this warning.
